---
title: "Docker Setup"
author: "Anna Lai"
date: "February 08, 2023"
output:
  html_document:
    toc: yes
    df_print: paged
---
# Docker Setup R Markdonw file with simple computations

## create a 5 by 10 matrix of random integers
```{r, warning=FALSE}
gene_matrix<- matrix(runif(n=50, min=0, max=50), nrow=5)
gene_matrix
```


## define column names as cond1, cond2, cond3, cond4, cond5, ctrl1, ctrl2, ctrl3, ctrl4, ctrl5
```{r}
colnames(gene_matrix)<- c("cond1", "cond2", "cond3", "cond4", "cond5"," ctrl1", "ctrl2", "ctrl3", "ctrl4", "ctrl5")
gene_matrix
```

## define row names as gene1, gene2, gene3 ...
```{r}
rownames(gene_matrix)<- c("gene1", "gene2", "gene3", "gene4", "gene5")
gene_matrix
```

## Compute the fold change for each gene.
```{r}
fold_c1 <- log2(gene_matrix[1]/gene_matrix[6])
fold_c2 <- log2(gene_matrix[2]/gene_matrix[7])
fold_c3 <- log2(gene_matrix[3]/gene_matrix[8])
fold_c4 <- log2(gene_matrix[4]/gene_matrix[9])
fold_c5 <- log2(gene_matrix[5]/gene_matrix[10])

fold_c1
fold_c2
fold_c3
fold_c4 
fold_c5 
```

